spring.application.name=voya-app
spring.datasource.url=jdbc:postgresql://db.vyjijmnpdkpkdpwppilt.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Andressabeatriz@pi3
spring.jpa.hibernate.ddl-auto=update