spring.application.name=voya-app
spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?user=postgres.vyjijmnpdkpkdpwppilt
spring.datasource.username=postgres
spring.datasource.password=Andressabeatriz@pi3
spring.jpa.hibernate.ddl-auto=update
jwt.secret=MJFDHUDSJSDNnjfdhUYUDSHBSNhdhsjhdUUIHD=YYERHENSAPOWWOJghdsgYGBhbUJI
ml.api.url=https://voya-app-springboot.onrender.com
server.port=${PORT:8080}